app/views/messages.py
""" Messages endpoints """
from flask import Blueprint, redirect, url_for, render_template, abort, jsonify
from flask_login import login_required, current_user
from .. import misc
from ..notifications import Notifications
from ..misc import engine, get_postmeta_dicts
from ..models import Notification

bp = Blueprint("messages", __name__)


@bp.route("/")
@login_required
def inbox_sort():
    """ Go to inbox with the new message """
    if misc.get_unread_count() > 0:
        return redirect(url_for("messages.view_messages"))
    elif misc.get_notif_count():
        return redirect(url_for("messages.view_notifications"))
    return redirect(url_for("messages.view_messages"))


@bp.route("/notifications", defaults={"page": 1})
@bp.route("/notifications/<int:page>")
@login_required
def view_notifications(page):
    notifications = Notifications.get_notifications(current_user.uid, page)
    # TODO: Move `lock-comments` to SubPost
    postmeta = get_postmeta_dicts(
        (n["pid"] for n in notifications if n["pid"] is not None)
    )

    for n in notifications:
        n["archived"] = False
        if n["cid"] or (n["pid"] and n["type"] not in ("POST_DELETE", "POST_UNDELETE")):
            n["archived"] = misc.is_archived(n)
            misc.add_blur(n)
        if (
            n["cid"]
            and n["already_viewed"] is not None
            and n["posted"] > misc.get_best_comment_sort_init_date()
            and not n["archived"]
        ):
            n["unseen"] = "unseen-comment"
        else:
            n["unseen"] = ""

    Notifications.mark_read(current_user.uid, notifications)
    return engine.get_template("user/messages/notifications.html").render(
        {"notifications": notifications, "postmeta": postmeta}
    )


@bp.route("/notifications/delete/<int:mid>", methods=["POST"])
@login_required
def delete_notification(mid):
    try:
        notification = Notification.get(
            (Notification.target == current_user.uid) & (Notification.id == mid)
        )
    except Notification.DoesNotExist:
        return abort(404)
    notification.delete_instance()
    return jsonify(status="ok")


@bp.route("/inbox", defaults={"page": 1})
@bp.route("/inbox/<int:page>")
@login_required
def view_messages(page):
    """ View user's messages """
    msgs = misc.get_messages_inbox(page)
    return render_template(
        "messages/messages.html",
        page=page,
        messages=msgs,
        box_name="Inbox",
        box_route="messages.view_messages",
    )


@bp.route("/sent", defaults={"page": 1})
@bp.route("/sent/<int:page>")
@login_required
def view_messages_sent(page):
    """ View user's messages sent """
    msgs = misc.get_messages_sent(page)
    return render_template(
        "messages/sent.html",
        messages=msgs,
        page=page,
        box_route="messages.view_messages_sent",
    )


@bp.route("/saved", defaults={"page": 1})
@bp.route("/saved/<int:page>")
@login_required
def view_saved_messages(page):
    """ WIP: View user's saved messages """
    msgs = misc.get_messages_saved(page)
    return render_template(
        "messages/saved.html",
        messages=msgs,
        page=page,
        box_route="messages.view_saved_messages",
    )

app/views/site.py
""" Miscellaneous site endpoints """
from peewee import SQL
from flask import Blueprint, redirect, url_for, abort, render_template
from flask_login import login_required, current_user
from .. import misc
from ..models import SiteLog, SubPost, SubLog, Sub, SubPostComment
from ..misc import engine
from ..config import config

bp = Blueprint("site", __name__)


@bp.route("/chat")
@login_required
def chat():
    if config.matrix.enabled:
        return redirect(config.matrix.webchat_url)
    if config.site.enable_chat:
        return engine.get_template("chat.html").render(
            {"subOfTheDay": misc.getSubOfTheDay(), "changeLog": misc.getChangelog()}
        )
    else:
        abort(404)


@bp.route("/sitelog", defaults={"page": 1})
@bp.route("/sitelog/<int:page>")
@login_required
def view_sitelog(page):
    """ Here we can see a log of admin activity on the site """

    if not config.site.sitelog_public and not current_user.can_admin:
        abort(404)

    s1 = SiteLog.select(
        SiteLog.time,
        SiteLog.action,
        SiteLog.desc,
        SiteLog.link,
        SiteLog.uid,
        SQL("'' as sub"),
        SiteLog.target,
    )
    s2 = SubLog.select(
        SubLog.time,
        SubLog.action,
        SubLog.desc,
        SubLog.link,
        SubLog.uid,
        Sub.name.alias("sub"),
        SubLog.target,
    )
    s2 = s2.join(Sub).where(SubLog.admin)
    logs = s1 | s2
    logs = logs.order_by(logs.c.time.desc()).paginate(page, 50)

    return engine.get_template("site/log.html").render({"logs": logs, "page": page})


@bp.route("/p/<pid>")
def view_post_inbox(pid):
    """ Gets route to post from just pid """
    try:
        post = SubPost.get(SubPost.pid == pid)
    except SubPost.DoesNotExist:
        return abort(404)
    return redirect(url_for("sub.view_post", sub=post.sid.name, pid=post.pid))


@bp.route("/c/<cid>")
def view_comment_inbox(cid):
    """ Gets route to post from just cid """
    try:
        comm = SubPostComment.get(SubPostComment.cid == cid)
    except SubPostComment.DoesNotExist:
        return abort(404)
    return redirect(
        url_for("sub.view_perm", sub=comm.pid.sid.name, pid=comm.pid_id, cid=comm.cid)
    )


@bp.route("/m/<sublist>", defaults={"page": 1})
@bp.route("/m/<sublist>/<int:page>")
def view_multisub_new(sublist, page=1):
    """ The multi index page, sorted as most recent posted first """
    names = sublist.split("+")
    if len(names) > 20:
        names = names[20:]

    subs = Sub.select(Sub.sid, Sub.name, Sub.title).where(Sub.name << names)
    sids = [x.sid for x in subs]

    posts = misc.getPostList(
        misc.postListQueryBase().where(Sub.sid << sids), "new", page
    )
    return render_template(
        "indexmulti.html",
        page=page,
        posts=posts,
        subs=subs,
        sublist=sublist,
        sort_type="site.view_multisub_new",
        kw={"subs": sublist},
    )


@bp.route("/activity")
def view_activity():
    return engine.get_template("site/activity.html").render(
        {
            # 'page': page,
            "subOfTheDay": misc.getSubOfTheDay(),
            "changeLog": misc.getChangelog(),
            "activity": misc.recent_activity(False),
        }
    )

app/views/sub.py
""" All endpoints related to stuff done inside of a particular sub """
import datetime
import time
from flask import Blueprint, redirect, url_for, abort, request, Response
from flask_login import login_required, current_user
from feedgen.feed import FeedGenerator
from peewee import fn, JOIN
from ..config import config
from ..misc import engine
from ..models import (
    Sub,
    SubMetadata,
    SubStylesheet,
    SubUploads,
    SubPostComment,
    SubPost,
    SubPostPollOption,
)
from ..models import (
    SubPostPollVote,
    SubPostMetadata,
    SubLog,
    User,
    UserSaved,
    SubMod,
    SubBan,
)
from ..models import (
    SubPostContentHistory,
    SubPostTitleHistory,
    SubPostReport,
    SubUserFlairChoice,
)
from ..forms import EditSubFlair, EditSubForm, EditSubCSSForm, EditMod2Form
from ..forms import (
    BanUserSubForm,
    CreateSubFlair,
    PostComment,
    AssignSubUserFlair,
)
from .. import misc


blueprint = Blueprint("sub", __name__)


@blueprint.route("/<sub>/")
@blueprint.route("/<sub>")
def view_sub(sub):
    """ Here we can view subs """
    if sub.lower() == "all":
        return redirect(url_for("home.all_hot", page=1))

    try:
        sub = Sub.get(fn.Lower(Sub.name) == sub.lower())
    except Sub.DoesNotExist:
        abort(404)

    try:
        x = SubMetadata.select().where(SubMetadata.sid == sub.sid)
        x = x.where(SubMetadata.key == "sort").get()
        x = x.value
    except SubMetadata.DoesNotExist:
        x = "v"
    if x == "v_two":
        return redirect(url_for("sub.view_sub_new", sub=sub.name))
    elif x == "v_three":
        return redirect(url_for("sub.view_sub_top", sub=sub.name))
    else:
        return redirect(url_for("sub.view_sub_hot", sub=sub.name))


@blueprint.route("/<sub>/edit/css")
@login_required
def edit_sub_css(sub):
    """ Here we can edit sub info and settings """
    try:
        sub = Sub.get(fn.Lower(Sub.name) == sub.lower())
    except Sub.DoesNotExist:
        abort(404)

    if not current_user.is_mod(sub.sid, 1) and not current_user.is_admin():
        abort(403)

    subInfo = misc.getSubData(sub.sid)
    subMods = misc.getSubMods(sub.sid)

    c = SubStylesheet.get(SubStylesheet.sid == sub.sid)

    form = EditSubCSSForm(css=c.source)
    stor = 0
    ufiles = SubUploads.select().where(SubUploads.sid == sub.sid)
    for uf in ufiles:
        stor += uf.size / 1024

    return engine.get_template("sub/css.html").render(
        {
            "sub": sub,
            "form": form,
            "error": False,
            "storage": int(stor),
            "max_storage": config.storage.sub_css_max_file_size,
            "files": ufiles,
            "subInfo": subInfo,
            "subMods": subMods,
        }
    )


@blueprint.route("/<sub>/edit/flairs")
@login_required
def edit_sub_flairs(sub):
    # Implemented by the modmail server.  This stub exists for use by url_for.
    abort(404)


@blueprint.route("/<sub>/edit/user_flairs")
@login_required
def edit_sub_user_flairs(sub):
    """ Here we manage user flairs """
    try:
        sub = Sub.get(fn.Lower(Sub.name) == sub.lower())
    except Sub.DoesNotExist:
        abort(404)

    if not current_user.is_mod(sub.sid, 1) and not current_user.is_admin():
        abort(403)

    flairs = SubUserFlairChoice.select().where(SubUserFlairChoice.sub == sub.sid)
    # assigned_flairs = SubUserFlair.select(SubUserFlair.flair_choice, SubUserFlair.flair, User.name)\
    #     .join(User).where(SubUserFlair.sub == sub.sid).dicts()

    assignflair = AssignSubUserFlair()

    formflairs = []
    for flair in flairs:
        formflairs.append(EditSubFlair(flair=flair.id, text=flair.flair))
        assignflair.flair_id.choices.append((flair.id, flair.flair))

    # formuserflairs = []
    # for flair in assigned_flairs:
    #     formuserflairs.append(EditSubUserFlair(flair=flair['flair_choice'], text=flair['flair'], user=flair['name']))

    return engine.get_template("sub/user_flairs.html").render(
        {
            "sub": sub,
            "flairs": formflairs,
            "createflair": CreateSubFlair(),  # 'assigned_flairs': formuserflairs,
            "assignflair": assignflair,
        }
    )


@blueprint.route("/<sub>/edit/rules")
@login_required
def edit_sub_rules(sub):
    # Implemented by the modmail server.  This stub exists for use by url_for.
    abort(404)


@blueprint.route("/<sub>/edit")
@login_required
def edit_sub(sub):
    """ Here we can edit sub info and settings """
    try:
        sub = Sub.get(fn.Lower(Sub.name) == sub.lower())
    except Sub.DoesNotExist:
        abort(404)

    if current_user.is_mod(sub.sid, 1) or current_user.is_admin():
        submeta = misc.metadata_to_dict(
            SubMetadata.select().where(SubMetadata.sid == sub.sid)
        )
        form = EditSubForm()
        # pre-populate the form.
        form.subsort.data = submeta.get("sort")
        form.sidebar.data = sub.sidebar
        form.title.data = sub.title

        return engine.get_template("sub/settings.html").render(
            {"sub": sub, "editsubform": form, "metadata": submeta}
        )
    else:
        abort(403)


@blueprint.route("/<sub>/sublog", defaults={"page": 1})
@blueprint.route("/<sub>/sublog/<int:page>")
def view_sublog(sub, page):
    """ Here we can see a log of mod/admin activity in the sub """
    try:
        sub = Sub.select().where(fn.Lower(Sub.name) == sub.lower()).dicts().get()
    except Sub.DoesNotExist:
        abort(404)

    subInfo = misc.getSubData(sub["sid"])
    if not config.site.force_sublog_public:
        log_is_private = subInfo.get("sublog_private", 0) == "1"

        if log_is_private and not (
            current_user.is_mod(sub["sid"], 1) or current_user.is_admin()
        ):
            abort(404)

    subMods = misc.getSubMods(sub["sid"])
    logs = (
        SubLog.select()
        .where(SubLog.sid == sub["sid"])
        .order_by(SubLog.lid.desc())
        .paginate(page, 50)
    )
    return engine.get_template("sub/log.html").render(
        {"sub": sub, "logs": logs, "page": page, "subInfo": subInfo, "subMods": subMods}
    )


@blueprint.route("/<sub>/mods")
@login_required
def edit_sub_mods(sub):
    """ Here we can edit moderators for a sub """
    try:
        sub = Sub.get(fn.Lower(Sub.name) == sub.lower())
    except Sub.DoesNotExist:
        abort(404)

    if (
        current_user.is_mod(sub.sid, 2)
        or current_user.is_modinv(sub.sid)
        or current_user.is_admin()
    ):
        subdata = misc.getSubData(sub.sid, extra=True)
        subMods = misc.getSubMods(sub.sid)
        modInvites = (
            SubMod.select(User.name, SubMod.power_level)
            .join(User)
            .where((SubMod.sid == sub.sid) & SubMod.invite)
        )
        return engine.get_template("sub/mods.html").render(
            {
                "sub": sub,
                "subdata": subdata,
                "editmod2form": EditMod2Form(),
                "subMods": subMods,
                "subModInvites": modInvites,
            }
        )
    else:
        abort(403)


@blueprint.route("/<sub>/new.rss")
def sub_new_rss(sub):
    """ RSS feed for /sub/new """
    try:
        sub = Sub.get(fn.Lower(Sub.name) == sub.lower())
    except Sub.DoesNotExist:
        abort(404)

    fg = FeedGenerator()
    fg.id(request.url)
    fg.title("New posts from " + sub.name)
    fg.link(href=request.url_root, rel="alternate")
    fg.link(href=request.url, rel="self")

    posts = misc.getPostList(
        misc.postListQueryBase(noAllFilter=True).where(Sub.sid == sub.sid), "new", 1
    )

    return Response(
        misc.populate_feed(fg, posts).atom_str(pretty=True),
        mimetype="application/atom+xml",
    )


@blueprint.route("/<sub>/new", defaults={"page": 1})
@blueprint.route("/<sub>/new/<int:page>")
def view_sub_new(sub, page):
    """ The index page, all posts sorted as most recent posted first """
    if sub.lower() == "all":
        return redirect(url_for("home.all_new", page=1))

    flair = request.args.get("flair")

    try:
        sub = Sub.select().where(fn.Lower(Sub.name) == sub.lower()).dicts().get()
    except Sub.DoesNotExist:
        abort(404)

    isSubMod = current_user.is_mod(sub["sid"], 1) or current_user.is_admin()

    posts = misc.getPostList(
        misc.postListQueryBase(noAllFilter=True, isSubMod=isSubMod, flair=flair).where(
            Sub.sid == sub["sid"]
        ),
        "new",
        page,
    )

    return engine.get_template("sub.html").render(
        {
            "sub": sub,
            "subInfo": misc.getSubData(sub["sid"]),
            "posts": posts,
            "page": page,
            "sort_type": "sub.view_sub_new",
            "subMods": misc.getSubMods(sub["sid"]),
            "flair": flair,
        }
    )


@blueprint.route("/<sub>/bannedusers")
def view_sub_bans(sub):
    """ See banned users for the sub """
    try:
        sub = Sub.get(fn.Lower(Sub.name) == sub.lower())
    except Sub.DoesNotExist:
        abort(404)

    subInfo = misc.getSubData(sub.sid)
    if not config.site.force_sublog_public:
        banned_users_is_private = subInfo.get("sub_banned_users_private", 0) == "1"

        if banned_users_is_private and not (
            current_user.is_mod(sub.sid, 1) or current_user.is_admin()
        ):
            abort(404)

    user = User.alias()
    created_by = User.alias()
    banned = SubBan.select(
        user, created_by, SubBan.created, SubBan.reason, SubBan.expires
    )
    banned = (
        banned.join(user, on=SubBan.uid)
        .switch(SubBan)
        .join(created_by, JOIN.LEFT_OUTER, on=SubBan.created_by_id)
    )
    banned = (
        banned.where(SubBan.sid == sub.sid)
        .where(SubBan.effective)
        .where(
            (SubBan.expires.is_null(True))
            | (SubBan.expires > datetime.datetime.utcnow())
        )
    )
    banned = banned.order_by(SubBan.created.is_null(True), SubBan.created.desc())

app/templates/indexmulti.html
{% extends "layout.html" %}
{% block title %}Multi - {{config.site.lema}}{% endblock %}

{% block sidebar %}
{{ super() }}
<div class="sidebarlists">
  <h4 class="center">New posts from:</h4>
  <ul>
    
    {% for sub in subs %}
      <li><a href="{{url_for('sub.view_sub', sub=sub.name)}}">/{{config.site.sub_prefix}}/{{sub.name}}</a>
      <div class="sidelocale">{{sub.title}}</div></li>
    {%endfor%}
  </ul>
</div>
{% endblock %}

{% block content %}
{{ super() }}
{% if not posts %}<h1 class="noshit">There are no posts here, yet.</h1>{% endif %}
<div class="alldaposts">
{% for post in posts if post.pid != func.getAnnouncement().pid %}
  {% include "indexpost.html" %}
{%endfor %}
</div>

{% if not kw %}
  {% set kw = {} %}
{%endif%}
{% if page > 1 %}
  <a href="{{url_for(sort_type, page=(page-1), sublist=sublist, **kw)}}" class="pure-button">prev</a>
{% endif %}
{% if posts|length == 25 %}
  <a href="{{url_for(sort_type, page=(page+1), sublist=sublist, **kw)}}" class="pure-button">next</a>
{% endif %}
{% endblock %}

{%block pagefoot%}
{%endblock%}

app/templates/indexpost.html
<div pid="{{post.pid}}" class="{% if post.deleted != 0 %}deletedpost {% endif %}post">
    <div class="misctainer">
      <div class="votebuttons">
        {% if post.userstatus != 10 and not func.is_archived(post) %}
        <div title="Upvote" class="upvote{%if post.positive == 1%} upvoted{%endif%}" data-pid="{{post.pid}}" data-icon="upvote"></div>
        <div class="score">{{post.score}}</div>
        <div title="Downvote" class="downvote{%if post.positive == 0%} downvoted{%endif%}" data-pid="{{post.pid}}" data-icon="downvote"></div>
        {%endif%}
      </div>
      <div class="thcontainer">
        <a href="{{url_for('sub.view_post', sub=post.sub, pid=post.pid)}}" class="title">
          <div class="thumbnail">
            {% if post.link != None %}
              {% if post.thumbnail == '' %}
                <span class="placeholder" data-icon="link"></span>
              {% elif post.thumbnail == 'deferred' %}
                <span class="placeholder deferred {{ post.blur }}" data-icon="link"
                      data-deferred="SubPost-{{ post.pid }}"></span>
              {% else %}
                <img class="lazy {{ post.blur }}" src="{{ url_for('static', filename='img/1x1.gif') }}"
                     data-src="{{ thumbnail_url(post.thumbnail) }}"/>
              {%endif %}
            {%else%}
              <span class="placeholder" data-icon="chat"></span>
            {% endif%}

          </div>
        </a>
      </div>
    </div>
    <div class="pbody">
      <div class="post-heading">
        {% if post.nsfw %}
        <div class="nsfw" alt="Not safe for work">{{_('NSFW')}}</div>
        {%endif%}
        {% if post.flair %}
          <a class="postflair" href="{{url_for('sub.view_sub_hot', sub=post.sub, flair=post.flair)}}">{{post.flair}}</a>
        {% endif %}
        {% if post.link == None %}
          <a href="{{url_for('sub.view_post', sub=post.sub, pid=post.pid)}}" class="title">
          {% if post.deleted == 1 %}
            {{_('[Deleted by User]')}}
          {% elif post.deleted in [2, 3] %}
            {{_('[Deleted by Mod or Admin]')}}
          {% endif %}
          <span class="{{ post.blur }}">{{post.title}}</span>
        </a>
        {% else %}
          {% if post.link.startswith('http:') %}<span title="not https" class="p-icon" data-icon="exclaim"></span>{% endif %}
          <a rel="noopener nofollow ugc" target="_blank" href="{{post.link}}" class="title">
            {% if post.deleted == 1 %}
              {{_('[Deleted by User]')}}
            {% elif post.deleted in [2, 3] %}
              {{_('[Deleted by Mod or Admin]')}}
            {% endif %}
            <span class="{{ post.blur }}">{{post.title}}</span>
          </a>
          <a href="{{url_for('home.all_domain_new', domain=func.getDomain(post.link), page=1)}}" class="domain">({{func.getDomain(post.link)}})</a>
        {% endif %}
      </div>
      <div class="author">
          {% if post.link %}
            {% if func.getDomain(post.link) in config.site.expando_sites %}
            <div class="expando" data-pid="{{post.pid}}" data-t="lnk" data-link="{{post.link}}"><div class="icon expando-btn" data-icon="play"></div></div>
            {% elif func.isImage(post.link) %}
            <div class="expando" data-pid="{{post.pid}}" data-t="lnk" data-link="{{post.link}}"><div class="icon expando-btn" data-icon="image"></div></div>
            {% elif func.isVideo(post.link) or func.isGifv(post.link) %}
            <div class="expando" data-pid="{{post.pid}}" data-t="lnk" data-link="{{post.link}}"><div class="icon expando-btn" data-icon="play"></div></div>
            {% endif %}
          {% elif post.content != '' %}
          <div class="expando" data-pid="{{post.pid}}" data-t="txt" data-link="{{post.link}}"><div class="icon expando-btn" data-icon="text"></div></div>
          {% endif %}
        posted <time-ago datetime="{{post.posted.isoformat()}}Z"></time-ago> by
        {% if post.userstatus != 10 %}
          <a class="authorlink" href="{{url_for('user.view', user=post.user)}}">{{post.user}}</a>
        {% endif %}
        {% if sub and post.pid in func.getStickyPid(sub.sid) %}
        - <span class="stick">sticky</span>
        {% endif %}
        {% if not sub %} on
        <a href="{{url_for('sub.view_sub', sub=post.sub)}}">{{post.sub}}</a>
        {%endif%}
      </div>
      <div class="links">
        <a class="comments" href="{{url_for('sub.view_post', sub=post.sub, pid=post.pid)}}">comments {%if post.comments>0%}({{post.comments}}){%endif%}</a>
      </div>
    </div>
</div>

app/templates/uploads.html
{% extends "layout.html" %}
{% block title %}Uploads | {{config.site.lema}}{% endblock %}

{% block sidebar %}
{{ super() }}
<a href="{{url_for('user.view', user=current_user.name)}}" class="sbm-post pure-button">{{current_user.name}}</a>
<a href="{{url_for('user.view_user_posts', user=current_user.name)}}" class="sbm-post pure-button">View posts</a>
<a href="{{url_for('user.view_user_comments', user=current_user.name)}}" class="sbm-post pure-button">View comments</a>
<a href="{{url_for('user.view_user_uploads')}}" class="sbm-post pure-button">View uploads</a>
<a href="{{url_for('user.view_user_savedposts', user=current_user.name)}}" class="sbm-post pure-button">View saved posts</a>
{% endblock %}

{% block content %}
{{ super() }}
{% if not uploads %}<h3 class="noshit">You haven't uploaded anything, yet.</h3>{% endif %}
<div id="center-container">
  <div class="uploads content">
      {% for item in uploads %}
        <div class="uploaditem">
          <div class="uploadthumb">
            {% if item.thumbnail == '' %}
              <span class="placeholder" data-icon="link"></span>
            {% elif item.thumbnail == 'deferred' %}
              <span class="placeholder deferred" data-icon="link"
                    data-deferred="UserUploads-{{ item.xid }}"></span>
            {% else %}
              <img class="lazy" src="{{ url_for('static', filename='img/1x1.gif') }}"
                   data-src="{{ thumbnail_url(item.thumbnail) }}"/>
            {% endif %}
          </div>
          <div class="uploadlinks">
            <div class="uploadlink"><a href="{{url_for('site.view_post_inbox', pid=item.pid_id)}}">View Post</a></div>
            <div class="uploadlink"><a href="{{file_url(item.fileid)}}">Direct Link</a></div>
          </div>
        </div>
      {% endfor %}
  </div>
</div>
<div class="col-12">
  {% if page > 1 %}
    <a href="{{url_for('user.view_user_uploads', page=(page-1))}}" class="pure-button">prev</a>
  {% endif %}
  {% if uploads|length == 30 %}
    <a href="{{url_for('user.view_user_uploads', page=(page+1))}}" class="pure-button">next</a>
  {% endif %}
</div>
{% endblock %}

app/templates/userposts.html
{% extends "layout.html" %}
{% block title %}Posts from /u/{{user.name}} | {{config.site.lema}}{% endblock %}

{% block sidebar %}
{{ super() }}
<a href="{{url_for('user.view', user=user.name)}}" class="sbm-post pure-button">{{user.name}}</a>
<a href="{{url_for('user.view_user_posts', user=user.name)}}" class="sbm-post pure-button">View posts</a>
<a href="{{url_for('user.view_user_comments', user=user.name)}}" class="sbm-post pure-button">View comments</a>
{% if user.uid == current_user.uid %}
  {% if current_user.canupload %}
    <a href="{{url_for('user.view_user_uploads')}}" class="sbm-post pure-button">View uploads</a>
  {% endif %}
  <a href="{{url_for('user.view_user_savedposts', user=user.name)}}" class="sbm-post pure-button">View saved posts</a>
{% endif %}
{% endblock %}

{% block content %}
{{ super() }}
{% if not current_user.is_authenticated and config.site.block_anon_stalking %}
    <div>Please log in to see this user's posts.</div>
{% else %}
    {% if sort_type == 'user.view_user_posts' %}
      <h3>Recent posts</h3>
      {% if user.status == 10 %}
        <div class="helper-text deleted-user">{{_("%(user)s has deleted their account.", user=user.name)}}</div>
      {% endif %}
    {% else %}
      <h3>Saved posts</h3>
    {% endif %}
    {% if not posts %}
      <h3>There are no posts here, yet.</h3>
    {% endif %}

    <div class="alldaposts">
    {% for post in posts %}
      {% include "indexpost.html" %}
    {%endfor%}
    </div>

    {% if page > 1 %}
      <a href="{{url_for(sort_type, page=(page-1), user=user.name)}}" class="pure-button">prev</a>
    {% endif %}
    {% if posts|length == 25 %}
      <a href="{{url_for(sort_type, page=(page+1), user=user.name)}}" class="pure-button">next</a>
    {% endif %}
{% endif %}
{% endblock %}